<a href="https://colab.research.google.com/github/Vputri/MiniTest/blob/main/Mini_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Program "ApaBole"   
  Print angka dari 1 sampai 100. Tetapi,:
1.   Untuk setiap angka yang bisa dibagi dengan 3, print "Apa". 
2.   Jika dapat dibagi dengan 5, print "Bole",
3. Jika dibagi oleh 3 dan 5, print "ApaBole".

In [1]:
def fizbuzz(n):
    for i in range(1, n+1):
        if i % 3 == 0 and i % 5 == 0:
            print("ApaBole", end=", ")
        elif i % 3 == 0:
            print("Apa", end=", ")
        elif i % 5 == 0:
            print("Bole", end=", ")
        else:
            print(i, end=", ")

fizbuzz(100)

1, 2, Apa, 4, Bole, Apa, 7, 8, Apa, Bole, 11, Apa, 13, 14, ApaBole, 16, 17, Apa, 19, Bole, Apa, 22, 23, Apa, Bole, 26, Apa, 28, 29, ApaBole, 31, 32, Apa, 34, Bole, Apa, 37, 38, Apa, Bole, 41, Apa, 43, 44, ApaBole, 46, 47, Apa, 49, Bole, Apa, 52, 53, Apa, Bole, 56, Apa, 58, 59, ApaBole, 61, 62, Apa, 64, Bole, Apa, 67, 68, Apa, Bole, 71, Apa, 73, 74, ApaBole, 76, 77, Apa, 79, Bole, Apa, 82, 83, Apa, Bole, 86, Apa, 88, 89, ApaBole, 91, 92, Apa, 94, Bole, Apa, 97, 98, Apa, Bole,

# Ramalan cuaca kota Jakarta untuk 5 hari kedepan 
Note : menggunakan API http://openweathermap.org

In [2]:
import requests

city = "Jakarta"
api_key = "8775bf099e83fd6c1987f58bc9b257a8"

url = 'http://api.openweathermap.org/data/2.5/weather?appid='+api_key+'&q='+city

req = requests.get(url)
data = req.json()

name = data['name']
lon = data['coord']['lon']
lat = data['coord']['lat']

#print(name, "is city at atitude : ", lat, "South and longitude : ", lon, "East")

In [3]:
import pandas as pd
url2 = 'http://api.openweathermap.org/data/2.5/forecast/?lat='+str(lat)+'&lon='+str(lon)+'&appid='+api_key

req2 = requests.get(url2)
data2 = req2.json()
temperature = []
date = []

for i in data2['list']:
  temperature.append(round(i['main']['temp'] - 273.15, 1))
  date.append(i['dt_txt'])

df = pd.DataFrame({'Datetime': date, 'Temperature': temperature}, columns=['Datetime', 'Temperature'])
df.head(1)

              Datetime  Temperature
0  2022-11-26 06:00:00         31.3

In [4]:
df['Date'] = pd.to_datetime(df['Datetime']).dt.strftime('%d %B %Y')
df['Time'] = pd.to_datetime(df['Datetime']).dt.time
df['Day'] = pd.to_datetime(df['Datetime']).dt.day_name()
df['Hour'] = pd.to_datetime(df['Datetime']).dt.hour
df.head(1)

,Datetime,Temperature,Date,Time,Day,Hour
0,2022-11-26 06:00:00,31.3,26 November 2022,06:00:00,Saturday,6

In [5]:
new_cols = ["Datetime","Day","Date","Time","Hour","Temperature"]
df=df[new_cols]
df.head(1)

,Datetime,Day,Date,Time,Hour,Temperature
0,2022-11-26 06:00:00,Saturday,26 November 2022,06:00:00,6,31.3

In [6]:
Hour_0 = df.loc[df['Hour'] == 0].reset_index(drop=True)
Hour_3 = df.loc[df['Hour'] == 3].reset_index(drop=True)
Hour_6 = df.loc[df['Hour'] == 6].reset_index(drop=True)
Hour_9 = df.loc[df['Hour'] == 9].reset_index(drop=True)
Hour_12 = df.loc[df['Hour'] == 12].reset_index(drop=True)
Hour_15 = df.loc[df['Hour'] == 15].reset_index(drop=True)
Hour_18 = df.loc[df['Hour'] == 18].reset_index(drop=True)
Hour_21 = df.loc[df['Hour'] == 21].reset_index(drop=True)

Hour_0.head(1)

              Datetime     Day              Date      Time  Hour  Temperature
0  2022-11-27 00:00:00  Sunday  27 November 2022  00:00:00     0         27.4

In [7]:
def forecast(data):
  print("Weather Forecast at "+str(data['Time'][0])+" :")
  for i in data.index:
      print(data['Day'][i]+", "+str(data['Date'][i])+": "+str(data['Temperature'][i]))
  print()

In [8]:
forecast(Hour_0)
forecast(Hour_3)
forecast(Hour_6)
forecast(Hour_9)
forecast(Hour_12)
forecast(Hour_15)
forecast(Hour_18)
forecast(Hour_21)

Weather Forecast at 00:00:00 :
Sunday, 27 November 2022: 27.4
Monday, 28 November 2022: 27.2
Tuesday, 29 November 2022: 26.9
Wednesday, 30 November 2022: 26.9
Thursday, 01 December 2022: 27.1

Weather Forecast at 03:00:00 :
Sunday, 27 November 2022: 29.0
Monday, 28 November 2022: 30.4
Tuesday, 29 November 2022: 29.5
Wednesday, 30 November 2022: 29.9
Thursday, 01 December 2022: 30.1

Weather Forecast at 06:00:00 :
Saturday, 26 November 2022: 31.3
Sunday, 27 November 2022: 30.9
Monday, 28 November 2022: 32.6
Tuesday, 29 November 2022: 30.8
Wednesday, 30 November 2022: 32.0

Weather Forecast at 09:00:00 :
Saturday, 26 November 2022: 31.7
Sunday, 27 November 2022: 29.9
Monday, 28 November 2022: 29.4
Tuesday, 29 November 2022: 29.9
Wednesday, 30 November 2022: 30.9

Weather Forecast at 12:00:00 :
Saturday, 26 November 2022: 28.7
Sunday, 27 November 2022: 28.5
Monday, 28 November 2022: 28.9
Tuesday, 29 November 2022: 28.3
Wednesday, 30 November 2022: 29.8

Weather Forecast at 15:00:00 :
Saturday, 26 November 2022: 26.9
Sunday, 27 November 2022: 28.1
Monday, 28 November 2022: 28.2
Tuesday, 29 November 2022: 28.1
Wednesday, 30 November 2022: 28.1

Weather Forecast at 18:00:00 :
Saturday, 26 November 2022: 26.9
Sunday, 27 November 2022: 27.5
Monday, 28 November 2022: 27.6
Tuesday, 29 November 2022: 27.5
Wednesday, 30 November 2022: 27.2

Weather Forecast at 21:00:00 :
Saturday, 26 November 2022: 26.9
Sunday, 27 November 2022: 26.7
Monday, 28 November 2022: 26.2
Tuesday, 29 November 2022: 26.6
Wednesday, 30 November 2022: 26.7